### PR TITLE
update deps, add WurdObject keys autodetect

### PR DESCRIPTION
**Pull request by caub**
@powmedia updated all deps, and added an autodetection of keys for WurdObject

when it has a `detect` prop, it'll detect inner keys from the children, and add them to the initial keys prop, if it exists
```jsx
<cms2.Object detect>
        <cms2.Text id="title" />
        <cms2.Text id="description" />
</cms2.Object>
```

note: it works only with wurd-react React components, not with a ` {cms2.text('title')}` for example

### CODE REVIEW

**Comment by caub** [comment]
Added examples/simple/build back, so that you could add a demo page: https://caub.github.io/wurd-react/examples/simple/build/?edit

https://wurdcms.github.io/wurd-react/examples/simple/build/?edit might already work, can you try to enable GH pages in settings?

**Comment by caub** [comment]
when I `npm link ../path/to/wurd-react` on another app, I get this error screen;
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

need to figure out why

**Comment by powmedia** [comment]
Thanks for the PR @caub - updating the deps and having the example site runnable on GH pages is great.  (I did enable GH pages but probably won't work until the PR is merged).

For the object keys, it would be very useful to have keys auto detect based on children however I don't think it should be done via this package.  wurd-react and wurd-web are meant to be as lean as possible because they are included in webpages that could have hundreds (maybe even thousands) of content items on them.  And most of the time the user will be viewing them outside of edit mode, so all they need to do is pass through the content.

I think the detect keys feature can be built in to the editor itself, which would have the advantages of:
- remain lean & lightweight until edit mode is turned on
- remain framework agnostic (would work with wurd-web, wurd-node and wurd-react)
- only need to lookup the keys at edit time, even specifically when the object itself is being edited

This should be relatively simple to do due to how DOM nodes are tagged up in edit mode and I am planning a couple of updates to the editor soon so will try to add that in.

Would welcome a separate PR with the other changes you've made though.

**Comment by caub** [comment]
Good points, yes the performance is important, that's a good concern

Actually doing it on the DOM was my initial idea, the issue is you can have have a React child component out of the DOM tree (Portals like modals, dropdowns too possibly), that's why I tried this React approach. We can probably link a possible portal by its idea, since usually popover need an id for accessibility anyway, so yea the DOM approach should work

the editor is in wurd-web?

I'll edit this MR to remove the detection changes

**Comment by caub** [comment]
done

**Comment by powmedia** [comment]
Thanks @caub!

Much easier to test changes to the lib from the example file now

**Comment by powmedia** [comment]
The example works on github pages now too: https://wurdcms.github.io/wurd-react/examples/simple/build/?edit

**Comment by caub** [comment]
Nice!

if you want you can put that demo link in the project description url https://github.com/wurdcms/wurd-react

**Comment by caub** [comment]
@powmedia where are the sources for this script: [https://edit-v3.wurd.io/widget.js](https://github.com/wurdcms/wurd-web/blob/master/src/index.js#L7)?

that's where we should make the WurdObject detect feature?

**Comment by powmedia** [comment]
That's the script that loads the editor, it's not on github though, so I'll add in the detect feature

**Pull request merged**
